[package]
name = "webgpu-samples"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"]}
env_logger = "0.10"
log = "0.4"
wgpu = "27.0.1"
pollster = "0.3"
bytemuck = { version = "1.24", features = [ "derive" ] }

